#!/usr/bin/perl

use strict;
use warnings;

my $ve_config_path = '/etc/vz/conf';

our $openvz_plan_binding = {
    '85'  => '10g',
    '77'  => '1g',
    '79'  => '1g',
};

my $plan_speed_binding = {
    '10g'   => '100000',
    '1g'   => '100000',
};

my $default_speed = "30000";

sub get_speed_by_ctid {
    my $ve = shift;
    my $plan_name = '';

    $plan_name = $openvz_plan_binding->{$ve};

    unless ($plan_name) {
        warn "no config for ve $ve \n";
        return $default_speed;
    }

    my $ve_speed = $plan_speed_binding->{$plan_name};

    unless ($ve_speed) {
        warn "no speed defined for plan $plan_name ve $ve \n";
        return $default_speed;
    }

    return $ve_speed;
}

1;

